#!/bin/bash
# The purpose of this wrapper script is (1) to determine the directory in which
# the websleydale Python package lives and (2) to execute $SCRIPT_NAME with the
# determined directory added to the Python path.

SCRIPT_NAME=websleydalerc.py

# Snippet from http://stackoverflow.com/a/246128, modified by Colin.
SOURCE=${BASH_SOURCE[0]}
while [[ -h $SOURCE ]]; do
  DIR=$(cd -P "$(dirname "$SOURCE")" && pwd)
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
done
WB_DIR=$(cd -P "$(dirname "$SOURCE")" && pwd)
# End snippet

if [[ -a $SCRIPT_NAME ]]; then
    PYTHONPATH=$WB_DIR python3 -m websleydale "$SCRIPT_NAME" "$@"
else
    echo >&2 "$0: no $SCRIPT_NAME found in the current directory"
    exit 1
fi
